# Generated by Django 4.0.4 on 2022-05-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='email@domain.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calories_exercise',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calories_food',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
